name: Build ARM Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
        
jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu_latest aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build arm64 binary
        id: runcmd
        with:
          arch: aarch64
          distro: alpine_latest
          
          env: |
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VERSION: ${{ github.ref_name }}
            MESSAGE: "WIP"
            NAME: ${{ github.ref_name }}
            FILES: hetzner-k3s-linux-arm64

          run: |
            apk add --update --no-cache gcc gmp-dev libevent-static musl-dev pcre-dev pcre2-dev libxml2-dev \
              libxml2-static openssl-dev openssl-libs-static tzdata yaml-static zlib-static xz-static \
              make git autoconf automake libtool patch
            apk add --update --no-cache libssh2-static libssh2-dev crystal shards github-cli
            shards install --without-development
            shards build --without-development --release --static
            cp ./bin/hetzner-k3s hetzner-k3s-linux-arm64
            ls -al
            git config --global --add safe.directory /home/runner/work/hetzner-k3s/hetzner-k3s
            #gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" || true
            #gh release upload ${{ env.VERSION }} ${{ env.FILES }}
            
      - name: Publish new version
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: derlinuxer/hetzner-k3s
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hetzner-k3s-linux-arm64
          tag: ${{ github.ref_name }}
          overwrite: true
          body: Test
